#!/usr/bin/env ruby


# For easier development
require "bundler/setup"
require_relative '../lib/mockarron/cli.rb'

# Should be this for real
# require 'mockarron'

# puts "Starting Mockarron..."
# Mockarron::WebServer.run!

Mockarron::CLI.start
