#!/usr/bin/env ruby


# For easier development
require "bundler/setup"
require_relative '../lib/mockarron/web_server.rb'

# Should be this for real
# require 'mockarron'

puts "Starting Mockarron..."
Mockarron::WebServer.run!
